[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
auto_detect_remappings = false
remappings = [
    "v4-core/=lib/v4-core/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/",
]

[fmt]
ignore = ["lib/**"]
